import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { useSession } from 'next-auth/react';

import "./globals.css";

import Profile from "@/components/profile";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const { data: session, status } = useSession();

    return (
        <>
            {session && (
            <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
            {children}
            <aside>
                <Profile />
            </aside>
            </body>
            </html>
            )}
            {!session && (
                <html lang="en">
                <body
                    className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                >
                    <Profile />
                </body>
                </html>
            )}
        </>
  );
}
